modLoader = "kotlinforforge"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "toshio"
version = "${version}"
displayName = "Tosh's IO mod"
authors = "gtosh4"
description = '''
Scalable and performant IO for items, fluids, energy, and more
'''

#logoFile = ""
[[dependencies.toshio]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toshio]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toshio]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"
